#!/bin/sh
if [ ! -f "/discovery/findface.token" ]; then
  check=$(curl -I -s -w "%{http_code}" -L "http://localhost:8000/" -o /dev/null)
  if [ $check -eq 404 ]; then
    findface-facenapi.token --short > /discovery/findface.token
  fi  
  exit 1
fi

