version: '2'
services:
  # parity:
  #   # image: "parity/parity:stable"
  #   image: '404247308186.dkr.ecr.us-east-1.amazonaws.com/parity:latest'
  #   restart: always
  #   container_name: "parity-${CHAIN}"
  #   working_dir: /parity/
  #   # see parity-settings.png
  #   # command: "--chain ${CHAIN} --jsonrpc-interface all --ws-interface all --ws-origins all --no-warp"
  #   volumes:
  #     - "$HOME/.parity/share/io.parity.ethereum/docker/${CHAIN}:/root/.local/share/io.parity.ethereum/"
  #   ports:
  #     # - 8180:8180
  #     - 8545:8545
  #     - 8546:8546
  #     - 30303:30303
  #     - 30303:30303/udp
  #   environment:
  #     NETWORK_NAME: "${CHAIN}"

  nginx:
    # image: '404247308186.dkr.ecr.us-east-1.amazonaws.com/nginx-proxy:latest'
    build: './nginx'
    ports:
      - 9876:80
    environment:
      HOST_TRUEFACE_SPOOF: tf-spoof:9877
      HOST_TRUEFACE_DASH: tf-spoof:9878
      # API_KEY: blah

  tf-spoof:
    image: '404247308186.dkr.ecr.us-east-1.amazonaws.com/tf-spoof:latest'
    ports:
      - 9877:80
    environment:

  tf-dash:
    image: '404247308186.dkr.ecr.us-east-1.amazonaws.com/tf-dash:latest'
    ports:
      - 9878:80
    environment:
