version: '2'
services:
  nginx:
    image: '404247308186.dkr.ecr.us-east-1.amazonaws.com/tradle-kyc-nginx-proxy:1.0.0'
    # container_name: tradle_vpc_nginx
    # build: './nginx'
    ports:
      - 9876:80
    environment:
      HOST_TRUEFACE_SPOOF: trueface-spoof
      PORT_TRUEFACE_SPOOF: 8085
      ENABLE_TRUEFACE_SPOOF: '1'
      HOST_TRUEFACE_DASH: trueface-dash
      PORT_TRUEFACE_DASH: 5000
      ENABLE_TRUEFACE_DASH: '0'
      HOST_RANK_ONE: rank-one
      PORT_RANK_ONE: 5000
      ENABLE_RANK_ONE: '1'
      NGINX_ENV_PATH: /etc/nginx/discovery/nginx.env
    volumes:
      - ./discovery:/etc/nginx/discovery

      # API_KEY: ""

  # trueface-spoof:
  #   container_name: trueface_spoof_tradle_vpc
  #   # build: './trueface-spoof'
  #   image: '404247308186.dkr.ecr.us-east-1.amazonaws.com/trueface-spoof:1.0.0'
  #   ports:
  #     - 8085:8085

  # # trueface-dash:
  # #   container_name: trueface_dash_tradle_vpc
  # #   build: './trueface-dash'
  # #   # image: '404247308186.dkr.ecr.us-east-1.amazonaws.com/trueface-dash:1.0.0'
  # #   ports:
  # #     - 5000:5000

  # rank-one:
  #   # container_name: rank_one_tradle_vpc
  #   image: '404247308186.dkr.ecr.us-east-1.amazonaws.com/rank-one:1.0.0'
  #   ports:
  #     - 8080:8080
